name: Generate GitHub Metrics
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate GitHub Metrics
      uses: lowlighter/metrics@latest
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        committer_token: ${{ secrets.GITHUB_TOKEN }}
        user: lndrdev
        template: classic
        base: header, activity, community, repositories, metadata
        config_timezone: UTC
